# Generated by Django 5.0.3 on 2024-05-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TOPIC',
            fields=[
                ('topic_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WEBPAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
                ('url', models.URLField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('topic_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ACCESS_RECORD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('author', models.CharField(default=None, max_length=50)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.webpage')),
            ],
        ),
    ]
